global:
    scrape_interval: 15s

scrape_configs:
    - job_name: 'nestjs_app'
      static_configs:
          - targets: ['host.docker.internal:3001']

    - job_name: 'prometheus_self'
      scrape_interval: 10s
      static_configs:
          - targets: ['localhost:9090']
